program Launcher;

uses
  Graphics,
  DGLEngine_header in '..\..\..\..\System\DGLEngine_header.pas';

{$R Ico.res}

var Font, Tex1, Tex2 : cardinal;
    B1, B2 : TBitmap;

procedure EngineInit;
begin
 Font:=LoadFontFromFile('..\..\Medium\Frustum Culling\TimeNewRoman_12.dft');

 B1:=TBitmap.Create;
 B1.LoadFromFile('Base.bmp');

 B2:=TBitmap.Create;
 B2.LoadFromFile('Alpha.bmp');

 Tex1:=LoadTexture(B1,TEXDETAIL_BEST,TRANSCOLOR_NONE,0,B2);

 B1.Free;
 B2.Free;

 Tex2:=LoadTextureFromFile('Base.bmp',TEXDETAIL_BEST,TRANSCOLOR_BLACK);

end;

procedure Draw;
begin
Begin2D;
DrawRectangle2D(0,0,GetScreenResX,GetScreenResY,$FF8000,255,true);

 DrawText2D(Font,15,50,'Alpha chanel generated from another BMP');
 DrawTexture2D_Simple(Tex1,-110,0,512,512);

 DrawText2D(Font,320,50,'Alpha chanel generated by key color (black) from single BMP');
 DrawTexture2D_Simple(Tex2,250,0,512,512);

End2D;
end;

procedure Process;
begin

 if IsKeyPressed(Key_Escape) then
 QuitEngine;

end;


begin
 if LoadDGLEngineDLL('..\..\..\System\DGLEngine.dll') then
 begin
  RegProcedure(PROC_DRAW,@Draw);
  RegProcedure(PROC_PROCESS,@Process);
  RegProcedure(PROC_INIT,@EngineInit);

  SetEngineInitParametrs(800,600,32,85,false,false,false);

  StartEngine;

  FreeDGLEngineDLL;
 end;

end.
